version: "3"

volumes:
  db_vol:

services:

  # We have 3 services: the database, the db init, and phpmyadmin
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: test_db
    restart: unless-stopped
    volumes:
      - db_vol:/var/lib/mysql
    ports:
      - "3306:3306"

  db_init:
    image: mysql:latest
    volumes:
      - ./:/app
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    entrypoint: [ "bash", "-c"]
    command:
      - |
        sleep 25 && \
        mysql \
        --user=root \
        --host=db \
        --port=3306 \
        --batch \
        test_db < /app/${SQL} > /app/result.txt && \
        exit
    depends_on:
      - db

  phpmyadmin:
      image: phpmyadmin:latest
      restart: unless-stopped
      ports:
          - 8080:80
      environment:
          # we specify that we connect to an arbitrary server with the flag below
          # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
          - PMA_ARBITRARY=1
      depends_on:
        - db_init
