version: "3"

volumes:
  db-vol:

services:

  # We have 3 services: the database, the db seeder, and phpmyadmin

  # pr_checker:
  #   image: kosehy/dood:env
  #   container_name: pr
  #   volumes:
  #     - db-vol:/src/gh/

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: test_db
    restart: unless-stopped
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - "3306:3306"

  db_seeder:
    image: mysql:latest
    volumes:
      - /data/gh/test_git_cli/${SQL}:/${SQL}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    entrypoint: [ "bash", "-c", "sleep 30 && mysql --user=root --host=db --port=3306 test_db < ./${SQL} && \
                                exit"]
    depends_on:
      - db

  phpmyadmin:
      image: phpmyadmin:latest
      restart: unless-stopped
      ports:
          - 8080:80
      environment:
          # we specify that we connect to an arbitrary server with the flag below
          # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
          - PMA_ARBITRARY=1
      depends_on:
        - db_seeder
